layout_spectrum: 0.6366595
typography_spectrum: 0.8255359
color:
  saturation: 0.4959766
  lightness: 0.507587
  brandStrength: 0.06681445
  rhythmicContrast: 0.6639069
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: plminsider1
