layout_spectrum: 0.08422939
typography_spectrum: 1
color:
  saturation: 0.4959766
  lightness: 0.507587
  brandStrength: 0.9910395
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#474747'
    - '#D4D4D4'
    - '#5C9AD4'
  rhythmicContrast: 0.6639069
name: plminsider
